### ISSUE TITLE
Downloading client gives me security warning

### ISSUE THREAD

**Issue by Jaydem808** [RBXLModders/Best-Late-2006-ROBLOX-Client-Remake#1]
Like the other clients during this time, it has a different security certificate.  Can you patch this please?

**Comment by RBXLModders** [comment]
> 
> 
> Like the other clients during this time, it has a different security certificate. Can you patch this please?

i dont know if i can but i will try soon

**Comment by Jaydem808** [comment]
Nevermind, fixed
